language: node_js
node_js:
  - "stable"
cache: npm
branches:
  only:
    - master
addons:
  ssh_known_hosts: git.wpengine.com
before_script:
  - cd wp-content/themes/modern-journalist
  - npm ci
script:
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_850ea7257488_key -iv $encrypted_850ea7257488_iv -in journalism_rsa.enc -out /tmp/journalism_rsa -d
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x deploy.sh && sh deploy.sh
    on:
      branch: master
